const member_list = {
  members: {
    ptarsoly: {
      img_src: "/images/ptarsoly.png",
      name: "Peter W. Tarsoly",
      major: "Computer Engineering",
      number: 1,
      class: "2021",
      origin: "Huntington, NY",
      catchphrase: "Goth girls will break your heart.",
    },
    gjacobellis: {
      img_src: "/images/gjacobellis.png",
      name: "Garrett A. Jacobellis",
      major: "Mechanical Engineering",
      number: 2,
      class: "2020",
      origin: "Huntington, NY",
      catchphrase: "Goth girls will break your heart.",
    },
    dmccook: {
      img_src: "/images/dmccook.png",
      name: "Dylan L. McCook",
      major: "Aerospace Engineering",
      number: 3,
      class: "2022",
      origin: "Liveoak, FL",
      catchphrase: "",
    },
    anoori: {
      img_src: "/images/anoori.png",
      name: "Amanda Noori",
      major: "Aerospace Engineering",
      number: 4,
      class: "2019",
      origin: "Atlanta, GA",
      catchphrase: "",
    },
    dsouthwell: {
      img_src: "/images/dsouthwell.png",
      name: "Donovan Southwell",
      major: "Aerospace Engineering",
      number: 5,
      class: "2020",
      origin: "Indiatlantic, FL",
      catchphrase: "",
    },
    msyed: {
      img_src: "/images/msyed.png",
      name: "Muntaser Syed",
      major: "Computer Engineering",
      number: 6,
      class: "2022",
      origin: "Abu Dhabi, UAE",
      catchphrase: "",
    },
    athierer: {
      img_src: "/images/athierer.png",
      name: "Alexander B. Thierer",
      major: "Civil Engineering",
      number: 7,
      class: "2019",
      origin: "High Point, NC",
      catchphrase: "",
    },
    athornton: {
      img_src: "/images/athornton.png",
      name: "Alana Thornton",
      major: "Mechanical Engineering",
      number: 8,
      class: "2019",
      origin: "Fort Washington, MD",
      catchphrase: "",
    },
    rwhitman: {
      img_src: "/images/rwhitman.png",
      name: "Robert Whitman",
      major: "Computer Science",
      number: 9,
      class: "2021",
      origin: "Palm Bay, FL",
      catchphrase: "",
    },
    fswarr: {
      img_src: "/images/fswarr.png",
      name: "Fiona E. Swarr",
      major: "Mechanical Engineering",
      number: 10,
      class: "2022",
      origin: "Melbourne, FL",
      catchphrase: "",
    },
    sedwards: {
      img_src: "/images/sedwards.png",
      name: "Sarah Edwards",
      major: "Aerospace Engineering",
      number: 11,
      class: "202",
      origin: "Brentwood, TN",
      catchphrase: "",
    },
    crush: {
      img_src: "/images/crush.png",
      name: "Cassandra Rush",
      major: "Aerospace Engineering",
      number: 12,
      class: "2022",
      origin: "Pittsburgh, PA",
      catchphrase: "",
    },
    ahopkins: {
      img_src: "/images/ahopkins.png",
      name: "Alexis Hopkins",
      major: "Biomedical Engineering",
      number: 13,
      class: "2021",
      origin: "",
      catchphrase: "",
    },
    mtapaszto: {
      img_src: "/images/mtapaszto.png",
      name: "Marcell Tapaszto",
      major: "Computer Engineering",
      number: 15,
      class: "2022",
      origin: "Kecskemet, Hungary",
      catchphrase: "",
    },
    measton: {
      img_src: "/images/measton.png",
      name: "Miranda Easton",
      major: "Aerospace Engineering",
      number: 16,
      class: "2023",
      origin: "Tallahassee, FL",
      catchphrase: "",
    },
    rgriffin: {
      img_src: "/images/rgriffin.png",
      name: "Ryley P. Griffin",
      major: "Chemical Engineering",
      number: 17,
      class: "2022",
      origin: "Morgantown, WV",
      catchphrase: "",
    },
    lblackwell: {
      img_src: "/images/lblackwell.png",
      name: "Landon C. Blackwell-Frank",
      major: "Mechanical Engineering",
      number: 18,
      class: "2024",
      origin: "The Woodlands, TX",
      catchphrase: "",
    },
    jhing: {
      img_src: "/images/jhing.png",
      name: "Justing Hing",
      major: "Aerospace Engineering",
      number: 19,
      class: "2022",
      origin: "fort Lauterdale, FL",
      catchphrase: "",
    },
    mhoadley: {
      img_src: "/images/mhoadley.png",
      name: "Michael Hoadley",
      number: 20,
      major: "Mechanical Engineering",
      class: "2022",
      origin: "Branford, CT",
      catchphrase: "Rockets and friends. Who needs more?",
    },
    ileon: {
      img_src: "/images/ileon.png",
      name: "Ian Leon",
      major: "Aerospace Engineering",
      number: 21,
      class: "2022",
      origin: "San Jose, Costa Rica",
      catchphrase: "Goth girls will break your heart.",
    },
    csisko: {
      img_src: "/images/csisko.png",
      name: "Caroline Sisko",
      major: "Aerospace Engineering",
      number: 22,
      class: "2022",
      origin: "Inverness, FL",
      catchphrase: "",
    },
    rhutchinson: {
      img_src: "/images/rhutchinson.png",
      name: "Ryan Hutchinson",
      major: "Aerospace Engineering",
      number: 23,
      class: "2022",
      origin: "Cocoa, FL",
      catchphrase: "",
    },
    dnieves: {
      img_src: "/images/dnieves.png",
      name: "David Nieves Acarón",
      major: "Computer Engineering",
      number: 24,
      class: "2022",
      origin: "San Juan, Puerto Rico",
      catchphrase: "",
    },
    grivasleal: {
      img_src: "/images/grivasleal.png",
      name: "Gerardo Rivas Leal",
      major: "Computer Engineering",
      number: 25,
      class: "2022",
      origin: "Labelle, FL",
      catchphrase: "",
    },
    atisaranni: {
      img_src: "/images/atisaranni.png",
      name: "Ashley L. Tisaranni",
      major: "Aerospace Engineering",
      number: 26,
      class: "2023",
      origin: "Germantown, MD",
      catchphrase: "",
    },
    kdecker: {
      img_src: "/images/kdecker.png",
      name: "Kayla N. Decker",
      major: "Aerospace Engineering",
      number: 27,
      class: "2022",
      origin: "Jacksonville, FL",
      catchphrase: "",
    },
    kforero: {
      img_src: "/images/kforero.png",
      name: "Kathleen Forero",
      major: "Chemical Engineering",
      number: 28,
      class: "2023",
      origin: "",
      catchphrase: "",
      include: false,
    },
    amichalczyk: {
      img_src: "/images/kforero.png",
      name: "Alaina M. Michalczyk",
      major: "Mechnical Engineering",
      number: 29,
      class: "2023",
      origin: "Chayna",
      catchphrase: "",
      include: false,
    },
    asullivan: {
      img_src: "/images/asullivan.png",
      name: "Adli R. Sullivan",
      major: "Chemical Engineering",
      number: 30,
      class: "2023",
      origin: "",
      catchphrase: "",
    },
    swaddell: {
      img_src: "/images/swaddell.png",
      name: "Shelton Waddell",
      major: "Aerospace Engineering",
      number: 31,
      class: "2023",
      origin: "Melbourne, FL",
      catchphrase: "",
    },
    rblomquist: {
      img_src: "/images/rblomquist.png",
      name: "Regan Blomquist",
      major: "Biomedical Engineering",
      number: 32,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    gmarrero: {
      img_src: "/images/gmarrero.png",
      name: "Jay Marrero",
      major: "Aerospace Engineering",
      number: 33,
      class: "2023",
      origin: "Flushing, NY",
      catchphrase: "",
    },
    kmobley: {
      img_src: "/images/kmobley.png",
      name: "Ken Mobley",
      major: "Aerospace Engineering",
      number: 34,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    tpaige: {
      img_src: "/images/tpaige.png",
      name: "Trent Paige",
      major: "Aerospace Engineering",
      number: 35,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    cswords: {
      img_src: "/images/cswords.png",
      name: "Carlie Swords",
      major: "Aerospace Engineering",
      number: 36,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    dbarnes: {
      img_src: "/images/dbarnes.png",
      name: "Dylan Barnes",
      major: "Aerospace Engineering",
      number: 37,
      class: "2022",
      origin: "",
      catchphrase: "",
    },
    rhalcyon: {
      img_src: "/images/rhalcyon.png",
      name: "Rosemary Halcyon-Schmitt",
      major: "Chemical Engineering",
      number: 38,
      class: "",
      origin: "",
      catchphrase: "",
    },

    jjohnson: {
      img_src: "/images/jjohnson.png",
      name: "Jordan Johnson",
      major: "Civil Engineering",
      number: 39,
      class: "2025",
      origin: "",
      catchphrase: "",
    },

    ajunkin: {
      img_src: "/images/ajunkin.png",
      name: "Andrew Junkin",
      major: "Biomedical Engineering",
      number: 40,
      class: "2023",
      origin: "",
      catchphrase: "",
    },
    mlanahan: {
      img_src: "/images/mlanahan.png",
      name: "Madison Lanahan",
      major: "Computer Science ",
      number: 41,
      class: "2026",
      origin: "",
      catchphrase: "",
    },
    dmcdaniels: {
      img_src: "/images/dmcdaniels.png",
      name: "Devlin McDaniels",
      major: "Aerospace Engineering",
      number: 42,
      class: "2022",
      origin: "",
      catchphrase: "",
    },
    vshirley: {
      img_src: "/images/vshirley.png",
      name: "Val Shirley",
      major: "Aerospace Engineering",
      number: 43,
      class: "2023",
      origin: "",
      catchphrase: "",
    },
    kweaver: {
      img_src: "/images/kweaver.png",
      name: "Keelin Weaver",
      major: "Aerospace Engineering",
      number: 44,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    czinninger: {
      img_src: "/images/czinninger.png",
      name: "Charlotte Zinninger",
      major: "Aerospace Engineering",
      number: 45,
      class: "2025",
      origin: "Syracyse, NY",
      catchphrase: "",
    },
    oloris: {
      img_src: "/images/oloris.png",
      name: "Olivia Loris",
      major: "Software Engineering",
      number: 46,
      class: "2026",
      origin: "",
      catchphrase: "",
    },
    gspitaletto: {
      img_src: "/images/gspitaletto.png",
      name: "Genevieve Spitaletto",
      major: "",
      number: 47,
      class: "",
      origin: "",
      catchphrase: "",
    },
    astringer: {
      img_src: "/images/astringer.png",
      name: "Ashton Stringer",
      major: "Mechanial Engineering",
      number: 48,
      class: "2025",
      origin: "",
      catchphrase: "",
    },
    zhardin: {
      img_src: "/images/zhardin.png",
      name: "Zachary Hardin",
      major: "Mechanical Engineering",
      number: 49,
      class: "2026",
      origin: "Rock Island, Illinois",
      catchphrase: "",
    },
    amoore: {
      img_src: "/images/amoore.png",
      name: "Archer Moore",
      major: "Chemical Engineering",
      number: 50,
      class: "2024",
      origin: "",
      catchphrase: "",
    },
    gmorales: {
      img_src: "/images/gmorales.png",
      name: "Gabriel Morales",
      major: "Software Engineering",
      number: 51,
      class: "2026",
      origin: "North Carolina",
      catchphrase: "",
    },
  },
};
export default member_list;
